# numpy



In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
print(a)
print(a.shape)
print(a2)
print(a2.shape)

[0 1 2 3 4 5]
(6,)
[[0 1 2 3 4 5]]
(1, 6)


[0 1 2 3 4 5]


[[0 1 2 3 4 5]]


In [3]:
a.ndim

1

In [4]:
a2.ndim

2

In [5]:
list1 = [1,2,3] #1차원
a = np.array(list1)
print(a)
print(a.shape)
print(a.ndim)

[1 2 3]
(3,)
1


In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]]) #2차원
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [7]:
c = np.array([[[1,2,3,4],[5,6,7,8]], [[9,10,11,12],[13,14,15,16]]]) #3차원
print(c)
print(c.shape)
print(c.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)
3


In [8]:
zero1 = np.zeros((3,3,3), dtype='int64')
print(zero1)
print(zero1.ndim,'차원')
print('\n')

one1 = np.ones((3,2,4),dtype='int64')
print(one1)
print(one1.ndim)
print('\n')

full1 = np.full((3,5), 10, dtype='int64')
print(full1)
print(full1.ndim)
print('\n')

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
3 차원


[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
3


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
2




In [9]:
range(12)
np.array(range(12)).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
range(24)
np.array(range(24)).reshape((3,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [11]:
np.arange(24).reshape((3,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [12]:
slice1 = np.arange(9).reshape((3,3))
print(slice1)
slice2 = slice1[0:2, 0:2]
print(slice2)
slice3 = slice1[1:,1:]
print(slice3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]
[[4 5]
 [7 8]]


In [13]:
a = [0,1,2,3]
print(b)
print(a[:2])
print(a[1:4:2]) #2칸 간격
print(a[::-1]) #뒤에서 1칸 간격(역순)


[[1 2 3 4]
 [5 6 7 8]]
[0, 1]
[1, 3]
[3, 2, 1, 0]


In [15]:
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(b[0][1])
print(b[0,1])
print(b[:2]) #0행에서 1행까지
print(b[:, 0]) #모든 행의 3열
print(b[0,:]) #0행의 모든 열
print(b[[0,2], :])
print(b[[2,0], :])

1
1
[[0 1 2 3]
 [4 5 6 7]]
[0 4 8]
[0 1 2 3]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 0  1  2  3]]


In [24]:
b_5 = b > 5
print(b_5)
print(b[b_5])
print(b[b > 5])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]
[ 6  7  8  9 10 11]


In [28]:
a = [0,1,2,3]
c = np.arange(4)
print(c)
print(a)
print(a + c)
print(c+1)

[0 1 2 3]
[0, 1, 2, 3]
[0 2 4 6]
[1 2 3 4]


In [42]:
a = np.arange(16).reshape((4,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [41]:
print(np.split(a, 2)) # 행을 기준으로 2개로 나눔

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [43]:
np.split(a,(1,3)) #tuple 일 때는 구간별로 나눔

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [48]:
splite1, splite2 = np.hsplit(a,2)
print(splite1)
print(splite2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [45]:
splite1, splite2 = np.vsplit(a,2)
print(splite1)
print(splite2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [58]:
a = np.arange(16).reshape(4,4)
stack0 = np.stack((a,a)) # axis = 0 이 기본값
print(stack0)
print(stack0.shape)
print(stack0.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]
(2, 4, 4)
3


In [59]:
stack1 = np.stack((a,a), axis = 1)
print(stack1)
print(stack1.shape)
print(stack1.ndim)

[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [12 13 14 15]]]
(4, 2, 4)
3


In [62]:
print(np.vstack((a,a)))
print(np.hstack((a,a)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


In [66]:
    a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
    print(a.flatten()) ##copy 방식
    print(a.ravel()) ##view 방식

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [70]:
aa = a.flatten()
print(aa)
aa[0] = 100
print(aa)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [74]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)
np.add(a,b)

[5 7 9]


array([5, 7, 9])

In [85]:
lst1 = [[1,2],[3,4]]
lst2 = [[1,2],[3,4]]
a = np.array(lst1)
b = np.array(lst2)
c = np.dot(a,b) #행렬의 곱
print(c)


a = np.array([[1,2],[3,4]])
print(a)
s = np.sum(a)
print(s)

s = np.sum(a, axis=0)
print(s)

s = np.sum(a, axis=1)
print(s)

s = np.prod(a)
print(s)

s = np.prod(a, axis=0)
print(s)

s = np.prod(a, axis=1)
print(s)

[[ 7 10]
 [15 22]]
[[1 2]
 [3 4]]
10
[4 6]
[3 7]
24
[3 8]
[ 2 12]


In [98]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [110]:
x = np.arange(10)
np.random.shuffle(x)
x

array([1, 2, 5, 0, 8, 3, 7, 9, 6, 4])

In [129]:
z = np.random.choice(5, 3, replace=False) #replace 가 true면 중복선택 가능, false면 중복선택 불가능
z

array([4, 3, 2])

In [128]:
z = np.random.choice(10,20, replace=True)
z

array([9, 7, 5, 3, 4, 5, 3, 3, 7, 9, 9, 9, 7, 3, 2, 3, 9, 7, 7, 5])

In [136]:
z = np.random.choice(5, 10, replace=True, p=[0.1,0,0.3,0.6,0])
z

array([2, 3, 3, 3, 2, 3, 3, 2, 2, 3])

In [137]:
a = [5,1,7,7,2,3,5]
x = np.unique(a)
x

array([1, 2, 3, 5, 7])

In [138]:
x, cnt = np.unique(a, return_counts=True)
print(x, cnt, sep=',')

[1 2 3 5 7],[1 1 1 2 2]
