# numpy



In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
print(a)
print(a.shape)
print(a2)
print(a2.shape)

[0 1 2 3 4 5]
(6,)
[[0 1 2 3 4 5]]
(1, 6)


In [3]:
a.ndim

1

In [4]:
a2.ndim

2

In [5]:
list1 = [1,2,3] #1차원
a = np.array(list1)
print(a)
print(a.shape)
print(a.ndim)

[1 2 3]
(3,)
1


In [6]:
b = np.array([[1,2,3,4],[5,6,7,8]]) #2차원
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [7]:
c = np.array([[[1,2,3,4],[5,6,7,8]], [[9,10,11,12],[13,14,15,16]]]) #3차원
print(c)
print(c.shape)
print(c.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)
3


In [8]:
zero1 = np.zeros((3,3,3), dtype='int64')
print(zero1)
print(zero1.ndim,'차원')
print('\n')

one1 = np.ones((3,2,4),dtype='int64')
print(one1)
print(one1.ndim)
print('\n')

full1 = np.full((3,5), 10, dtype='int64')
print(full1)
print(full1.ndim)
print('\n')

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
3 차원


[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]
3


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]
2




In [9]:
range(12)
np.array(range(12)).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
range(24)
np.array(range(24)).reshape((3,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [11]:
np.arange(24).reshape((3,4,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [12]:
slice1 = np.arange(9).reshape((3,3))
print(slice1)
slice2 = slice1[0:2, 0:2]
print(slice2)
slice3 = slice1[1:,1:]
print(slice3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]
[[4 5]
 [7 8]]


In [13]:
a = [0,1,2,3]
print(b)
print(a[:2])
print(a[1:4:2]) #2칸 간격
print(a[::-1]) #뒤에서 1칸 간격(역순)


[[1 2 3 4]
 [5 6 7 8]]
[0, 1]
[1, 3]
[3, 2, 1, 0]


In [15]:
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(b[0][1])
print(b[0,1])
print(b[:2]) #0행에서 1행까지
print(b[:, 0]) #모든 행의 3열
print(b[0,:]) #0행의 모든 열
print(b[[0,2], :])
print(b[[2,0], :])

1
1
[[0 1 2 3]
 [4 5 6 7]]
[0 4 8]
[0 1 2 3]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 8  9 10 11]
 [ 0  1  2  3]]


In [24]:
b_5 = b > 5
print(b_5)
print(b[b_5])
print(b[b > 5])

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]
[ 6  7  8  9 10 11]


In [28]:
a = [0,1,2,3]
c = np.arange(4)
print(c)
print(a)
print(a + c)
print(c+1)

[0 1 2 3]
[0, 1, 2, 3]
[0 2 4 6]
[1 2 3 4]
