In [10]:
import pandas as pd
import numpy as np

In [30]:
a = np.arange(9)
pd.DataFrame({'a': a})

a
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8

In [34]:
s = pd.Series([1,3,5,7,9])
print(s,'\n')
print(s.index,'\n')
print(s.values)

0    1
1    3
2    5
3    7
4    9
dtype: int64 

RangeIndex(start=0, stop=5, step=1) 

[1 3 5 7 9]


In [44]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
print(s,'\n')
print(pd.Series(range(1,10)),'\n')
print(s.index,'\n')
print(s.values,'\n')
s.name = '인구'
s.index.name = '도시'

print(s,'\n')

s.index.name = None
print(s,'\n')

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64 

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64 

Index(['서울', '부산', '인천', '대구'], dtype='object') 

[9904312 3448737 2890451 2466052] 

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64 

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64 



In [47]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
s = s / 1000000
print(s,'\n')
print(s[1:3],'\n')
print(s['서울'],'\n')

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64 

부산    3.448737
인천    2.890451
dtype: float64 

9.904312


In [49]:
s1 = pd.Series(range(3), index=['a','b','c'])
print(s1,'\n')
print(s1.a,'\n')
print(s1['a'])

a    0
b    1
c    2
dtype: int64 

0 

0


In [60]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
print('대구' in s,'\n')
print('대전' in s,'\n')
for key, value in s.items():
    print('{0},{1}'.format(key, value))

for key in s.keys():
    print('{0}'.format(key))
print(s.values)

True 

False 

서울,9904312
부산,3448737
인천,2890451
대구,2466052
서울
부산
인천
대구
[9904312 3448737 2890451 2466052]


In [68]:
s = pd.Series({'국어':90, '영어':80, '수학':70})
print(s,'\n')
print(s.index,'\n')
print(s.values,'\n')

s2 = pd.Series({'서울':9000000,'부산':8000000,'인천':7000000,'대전':6000000})
print(s2,'\n')
print(s2.index,'\n')
s2 = pd.Series({'서울':9000000,'부산':8000000,'인천':7000000,'대전':6000000}, index=['부산','서울','인천','대전'])
print(s2)

국어    90
영어    80
수학    70
dtype: int64 

Index(['국어', '영어', '수학'], dtype='object') 

[90 80 70] 

서울    9000000
부산    8000000
인천    7000000
대전    6000000
dtype: int64 

Index(['서울', '부산', '인천', '대전'], dtype='object') 

부산    8000000
서울    9000000
인천    7000000
대전    6000000
dtype: int64


In [71]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
s2 = pd.Series({'서울':9631482,'부산':3393191,'인천':2632035,'대전':1490158},index=['부산','서울','인천','대전'])
ds = s - s2
print(ds,'\n')
print(s.values - s2.values,'\n')
print(ds.notnull(),'\n')
print(ds[ds.notnull()],'\n')
rs = (s - s2)/ s2 * 100 #인구 증가율
rs = rs[rs.notnull()]
print(rs)

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64 

[ 6511121 -6182745   258416   975894] 

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool 

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64 

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64


In [74]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141