In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.arange(9)
pd.DataFrame({'a': a})

a
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8

In [3]:
s = pd.Series([1,3,5,7,9])
print(s,'\n')
print(s.index,'\n')
print(s.values)

0    1
1    3
2    5
3    7
4    9
dtype: int64 

RangeIndex(start=0, stop=5, step=1) 

[1 3 5 7 9]


In [4]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
print(s,'\n')
print(pd.Series(range(1,10)),'\n')
print(s.index,'\n')
print(s.values,'\n')
s.name = '인구'
s.index.name = '도시'

print(s,'\n')

s.index.name = None
print(s,'\n')

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64 

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64 

Index(['서울', '부산', '인천', '대구'], dtype='object') 

[9904312 3448737 2890451 2466052] 

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64 

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64 



In [5]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
s = s / 1000000
print(s,'\n')
print(s[1:3],'\n')
print(s['서울'],'\n')

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
dtype: float64 

부산    3.448737
인천    2.890451
dtype: float64 

9.904312 



In [6]:
s1 = pd.Series(range(3), index=['a','b','c'])
print(s1,'\n')
print(s1.a,'\n')
print(s1['a'])

a    0
b    1
c    2
dtype: int64 

0 

0


In [7]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
print('대구' in s,'\n')
print('대전' in s,'\n')
for key, value in s.items():
    print('{0},{1}'.format(key, value))

for key in s.keys():
    print('{0}'.format(key))
print(s.values)

True 

False 

서울,9904312
부산,3448737
인천,2890451
대구,2466052
서울
부산
인천
대구
[9904312 3448737 2890451 2466052]


In [8]:
s = pd.Series({'국어':90, '영어':80, '수학':70})
print(s,'\n')
print(s.index,'\n')
print(s.values,'\n')

s2 = pd.Series({'서울':9000000,'부산':8000000,'인천':7000000,'대전':6000000})
print(s2,'\n')
print(s2.index,'\n')
s2 = pd.Series({'서울':9000000,'부산':8000000,'인천':7000000,'대전':6000000}, index=['부산','서울','인천','대전'])
print(s2)

국어    90
영어    80
수학    70
dtype: int64 

Index(['국어', '영어', '수학'], dtype='object') 

[90 80 70] 

서울    9000000
부산    8000000
인천    7000000
대전    6000000
dtype: int64 

Index(['서울', '부산', '인천', '대전'], dtype='object') 

부산    8000000
서울    9000000
인천    7000000
대전    6000000
dtype: int64


In [58]:
s = pd.Series([9904312,3448737,2890451,2466052], index=['서울','부산','인천','대구'])
s2 = pd.Series({'서울':9631482,'부산':3393191,'인천':2632035,'대전':1490158},index=['부산','서울','인천','대전'])
ds = s - s2
print(ds,'\n')
print(s.values - s2.values,'\n')
print(ds.notnull(),'\n')
print(ds[ds.notnull()],'\n')
rs = (s - s2)/ s2 * 100 #인구 증가율
rs = rs[rs.notnull()]
rs

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64 

[ 6511121 -6182745   258416   975894] 

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool 

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64 



부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

In [10]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [61]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df[['지역']]

지역
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [63]:
df[['2010','2015']]

2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [54]:
type(df[['2010']])

pandas.core.frame.DataFrame

In [57]:
df2 = pd.DataFrame(np.arange(12).reshape(3,4))
df2[[2]]

2
0   2
1   6
2  10

# 타이타닉 데이터프레임
* passengerId: 승객의 아이디
* survived: 생존여부
* Pclass : 승객 등급
* name: 승객 이름
* sex: 성별
* age : 나이
* sibsp : 동승한 배우자와 형제(자매)수
* parch : 동승한 부모님 수와 자식수
* ticket : 티켓 번호
* fare : 운임 요금
* cabin : 객실 구역
* embarked: 어디서 탑승했는지 등에 대한 정보

In [13]:
import pandas as pd
df = pd.read_csv('./titanic/train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [17]:
df.head() #상위 5개를 읽어옴

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [16]:
df.tail() #하위 5개를 읽어옴

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [18]:
df.sample(10) #숫자만큼 무작위 순서로 읽어옴

PassengerId  Survived  Pclass                                   Name  \
746          747         0       3            Abbott, Mr. Rossmore Edward   
346          347         1       2              Smith, Miss. Marion Elsie   
646          647         0       3                      Cor, Mr. Liudevit   
475          476         0       1            Clifford, Mr. George Quincy   
375          376         1       1  Meyer, Mrs. Edgar Joseph (Leila Saks)   
744          745         1       3                     Stranden, Mr. Juho   
30            31         0       1               Uruchurtu, Don. Manuel E   
115          116         0       3                  Pekoniemi, Mr. Edvard   
520          521         1       1                  Perreault, Miss. Anne   
324          325         0       3               Sage, Mr. George John Jr   

        Sex   Age  SibSp  Parch             Ticket     Fare Cabin Embarked  
746    male  16.0      1      1          C.A. 2673  20.2500   NaN        S  
346  female  40.0      0      0              31418  13.0000   NaN        S  
646    male  19.0      0      0             349231   7.8958   NaN        S  
475    male   NaN      0      0             110465  52.0000   A14        S  
375  female   NaN      1      0           PC 17604  82.1708   NaN        C  
744    male  31.0      0      0  STON/O 2. 3101288   7.9250   NaN        S  
30     male  40.0      0      0           PC 17601  27.7208   NaN        C  
115    male  21.0      0      0  STON/O 2. 3101294   7.9250   NaN        S  
520  female  30.0      0      0              12749  93.5000   B73        S  
324    male   NaN      8      2           CA. 2343  69.5500   NaN        S

In [19]:
 df.info() #dataFrame에 대한 기본 정보를 요약

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [34]:
df.isna() #결측값을 파악, 값이 None일 경우 True, 값이 정상적으로 채워져있는경우 false를 반환

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [21]:
df.describe() #숫자형 열에 대한 기초 통계를 분석
#총 갯수(count),평균(mean),표준 편차(std),최솟값,최댓값등

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [46]:
df.describe(include='all')

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [23]:
df.corr() #숫자형 열 간의 상관관계를 구함

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare         1.000000

In [32]:
df.mean() #평균

C:\Project\AI_Source\AI_01\venv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [25]:
df.groupby('Survived').mean() #데이터를 그룹별로 집계

PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived                                                                 
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [35]:
df.groupby(['Sex','Survived']).mean()

PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived                                                         
female 0          434.851852  2.851852  25.046875  1.209877  1.037037   
       1          429.699571  1.918455  28.847716  0.515021  0.515021   
male   0          449.121795  2.476496  31.618056  0.440171  0.207265   
       1          475.724771  2.018349  27.276022  0.385321  0.357798   

                      Fare  
Sex    Survived             
female 0         23.024385  
       1         51.938573  
male   0         21.960993  
       1         40.821484

In [36]:
df1 = df.rename({'Name': '이름'}, axis=1)
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                    이름     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [40]:
df2 = df.rename(columns={'Age':'나이','Name':'이름','Sex':'성별'})
df2

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                    이름      성별    나이  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [29]:
df3 = df.Sex.map(lambda x: 0 if x == 'female' else 1) #성별이 여자면 0, 남자면 1로 변환
df3

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [42]:
def convert_gender(x):
    if x == 'Female':
        return 0
    else:
        return 1
df3 = df.Sex.map(convert_gender)
df3

0      1
1      1
2      1
3      1
4      1
      ..
886    1
887    1
888    1
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [43]:
def convert_Embarked(x):
    if x == 'C':
        return 0
    elif x == 'Q':
        return 1
    else:
        return 2

df3 = df.Embarked.map(convert_Embarked)
df3

0      2
1      0
2      2
3      2
4      2
      ..
886    2
887    2
888    2
889    0
890    1
Name: Embarked, Length: 891, dtype: int64

In [30]:
def n_square(x,n):
    return x ** n
df4 = df[['Age','SibSp','Fare']].apply(n_square, n=2)
df4

Age  SibSp         Fare
0     484.0      1    52.562500
1    1444.0      1  5081.308859
2     676.0      0    62.805625
3    1225.0      1  2819.610000
4    1225.0      0    64.802500
..      ...    ...          ...
886   729.0      0   169.000000
887   361.0      0   900.000000
888     NaN      1   549.902500
889   676.0      0   900.000000
890  1024.0      0    60.062500

[891 rows x 3 columns]

In [49]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64