### TensorFlow
* 개념
    * tensorflow는 대규모 숫자 계산을 해주는 라이브러리이다.
    * tensor는 다양한 행렬계산을 흐르게 한다는 의미이다.
    * tensorflow는 일단 계산식을 먼저 만들어 놓고 데이터를 하나하나 넣으며 실행하는 구조이다.
    * 일부 영상처리 기능도 가지고 있으며 그때는 openCV라이브러리 등과 함께 사용한다.

* 텐서(Tensor)
    * 텐서플로우는 스칼라, 벡터, 행렬과 같은 모든 데이터를 텐서(Tensor)로 인식한다.
        - 숫자 1,2,3 : 스칼라(Scala)
        - 1차원 배열 : 벡터(Vector)
        - 2차원 배열 : 행렬(Metrix)
        - 3차원 배열 : 텐서(Tensor)

* 텐서플로우 노드(Node) / 엣지(Edge)
    * 텐서플로우 코드를 구현 할 때에는 다음의 두가지 단계로 진행한다.
        - 상수,변수,텐서 연산 등의 노드와 이들을 연결해주는 엣지를 정의한다.
        - 세션(Session)을 만들고 그 세션을 통해 노드에 있는 데이터(텐서)가 전달되고 연산이 이루어진다.

In [9]:
import tensorflow as tf
#상수 노드 정의
a = tf.constant(1.0)
b = tf.constant(2.0)
c = tf.constant([ [1.0, 2.0], [3.0, 4.0] ])
print(a)
print(a+b)
print(c)
tf.__version__


Tensor("Const_15:0", shape=(), dtype=float32)
Tensor("add_11:0", shape=(), dtype=float32)
Tensor("Const_17:0", shape=(2, 2), dtype=float32)


'1.15.0'

In [10]:
# 세션(session) 을 만들고 노드간의 텐서 연산 실행
sess = tf.Session()
print(sess.run([a,b]))
print(sess.run(c))
print(sess.run([a+b]))
print(sess.run(c+1.0)) # brodcast(모든 데이터에 특정 값을 연산) 수행

# 세션 close
sess.close()

[1.0, 2.0]
[[1. 2.]
 [3. 4.]]
[3.0]
[[2. 3.]
 [4. 5.]]


In [11]:
# tensorflow 읽어 들이기
import tensorflow as tf

# 상수 정의하기
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

#연산 정의하기
calc1_op = a + b * c
calc2_op = (a+b) * c

#세션 시작하기
sess = tf.Session()
res1 = sess.run(calc1_op)
print(res1)

res2 = sess.run(calc2_op)
print(res2)

sess.close()

14
20


In [12]:
# 플레이스홀더 노드

import tensorflow as tf

#플레이스홀더 노드 정의
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = a + b

#세션을 만들고 플레이스홀더 노드를 통해 값 입력받음
sess = tf.Session()
print(sess.run(c, feed_dict={a:1.0, b:3.0}))
print(sess.run(c, feed_dict={a:[1.0, 2.0], b:[3.0, 4.0]}))
sess.close()

4.0
[4. 6.]


In [15]:
import tensorflow as tf

a = tf.placeholder(tf.int32, [3]) #정수 자료형 3개를 가진 배열

#배열을 모든 값을 2배하는 연산 정의하기
b = tf.constant(2)
x2_op = a * b

#세션 시작하기
sess = tf.Session()

#플레이스홀더에 값 넣고 실행ㅎ기
r1 = sess.run(x2_op, feed_dict={a:[1,2,3]})
print(r1)

r2 = sess.run(x2_op, feed_dict={a:[10,20,30]})
print(r2)

sess.close()

[2 4 6]
[20 40 60]


In [19]:
# 변수 노드

import tensorflow as tf

#값이 업데이트되는 변수노드 정의

w1 = tf.Variable(tf.random_normal([1])) #난수발생하는 함수
b1 = tf.Variable(tf.random_normal([1]))
w2 = tf.Variable(tf.random_normal([1,2]))
b2 = tf.Variable(tf.random_normal([1,2]))

sess = tf.Session()

#변수노드 값 초기화, 변수노드를 정의했다면 반드시 필요함
sess.run(tf.compat.v1.global_variables_initializer())

for step in range(3):
    w1 = w1 - step
    b1 = b1 - step
    w2 = w2 - step
    b2 = b2 - step
    print("step = ", step, ", W1 = ", sess.run(w1), ", b1 = ", sess.run(b1))
    print("step = ", step, ", W2 = ", sess.run(w2), ", b2 = ", sess.run(b2))
sess.close()


step =  0 , W1 =  [1.0016055] , b1 =  [-0.08536478]
step =  0 , W2 =  [[-0.1359696 -1.7619481]] , b2 =  [[-1.6478444 -1.134392 ]]
step =  1 , W1 =  [0.00160551] , b1 =  [-1.0853648]
step =  1 , W2 =  [[-1.1359696 -2.761948 ]] , b2 =  [[-2.6478443 -2.134392 ]]
step =  2 , W1 =  [-1.9983945] , b1 =  [-3.0853648]
step =  2 , W2 =  [[-3.1359696 -4.761948 ]] , b2 =  [[-4.6478443 -4.134392 ]]


In [21]:
import tensorflow as tf

#feeding 값 선언
input_data = [1,2,3,4,5]

#placeholder 변수 선언
x = tf.placeholder(dtype=tf.float32)

#w = 2 라는 값 선언
w = tf.Variable([2], dtype=tf.float32)
y = w * x

sess = tf.Session()

# 변수 초기화
sess.run(tf.global_variables_initializer())

# y그래프에 input_data feeding 하면서 세션 실행
result = sess.run(y,feed_dict={x:input_data})
print(result)

#세션 close
sess.close()

[ 2.  4.  6.  8. 10.]


In [22]:
import tensorflow as tf

a = tf.constant(120)
b = tf.constant(130)
c = tf.constant(140)
v = tf.Variable(0)

#데이터에 플로우 그래프 정의하기
calc_op = a+b+c

#두번째 파라미터를 첫번째 파라미터에 대입함
assign_op = tf.compat.v1.assign(v, calc_op)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(assign_op)

#v의 내용 출력하기
print(sess.run(v))
sess.close()


390


In [39]:
import pandas as pd
import numpy as np
import tensorflow as tf

#bmi 파일 읽기
csv = pd.read_csv('../../AI머신러닝데이터/bmi.csv')

#데이터 정규화
csv['height'] = csv['height'] / 200
csv['weight'] = csv['weight'] / 100

#레이블을 배열로 변환하기
bclass = {'thin':[1,0,0], 'normal':[0,1,0], 'fat':[0,0,1]}
csv['label_pat'] = csv['label'].apply(lambda x: np.array(bclass[x]))

#테스트를 위한 데이터 분류
test_csv = csv[15000:20000]
test_pat = test_csv[['weight','height']]
test_ans = list(test_csv['label_pat'])

In [45]:
# 플레이스 홀더 선언
x = tf.placeholder(tf.float32, [None, 2]) #키와 몸무게 데이터 넣기, 2차원 구조
y_ = tf.placeholder(tf.float32, [None, 3])

#변수 선언하기
w = tf.Variable(tf.zeros([2,3])) # 가중치
b = tf.Variable(tf.zeros([3])) # bias

#소프트맥스 회귀(다중분류) 정의하기
y = tf.nn.softmax(tf.matmul(x,w) + b)

In [46]:
#모델 훈련하기
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=y, labels=y_))

#GradientDescentOptimizer : 경사하강법으로 손실 함수를 최소화하는 모델 파라미터를 찾기 위해 사용
#0.01은 학습률
optimizer = tf.train.GradientDescentOptimizer(0.01) 
train = optimizer.minimize(cross_entropy)

#정답률 구하기
predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(predict, tf.float32)) # tf.cast() : 캐스트 연산에 사용


In [47]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

#학습시키기
for step in range(15000):
    i = (step * 100) % 15000
    rows = csv[1 + i : 1 + i + 100]
    x_pat = rows[["weight","height"]]
    y_ans = list(rows["label_pat"])
    fd = {x: x_pat, y_: y_ans}
    sess.run(train, feed_dict=fd)
    if step % 500 == 0:
        cre = sess.run(cross_entropy, feed_dict=fd)
        acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
        print("step=", step, "cre=", cre, "acc=", acc)


step= 0 cre= 1.098595 acc= 0.3242
step= 500 cre= 1.0949001 acc= 0.3684
step= 1000 cre= 1.0968362 acc= 0.3684
step= 1500 cre= 1.0890875 acc= 0.3684
step= 2000 cre= 1.0854574 acc= 0.3684
step= 2500 cre= 1.0907798 acc= 0.3684
step= 3000 cre= 1.0794799 acc= 0.3772
step= 3500 cre= 1.0763575 acc= 0.4024
step= 4000 cre= 1.082489 acc= 0.433
step= 4500 cre= 1.0693377 acc= 0.4796
step= 5000 cre= 1.0670123 acc= 0.5142
step= 5500 cre= 1.0734547 acc= 0.5468
step= 6000 cre= 1.058941 acc= 0.5828
step= 6500 cre= 1.0574982 acc= 0.6054
step= 7000 cre= 1.064285 acc= 0.6246
step= 7500 cre= 1.0485251 acc= 0.6442
step= 8000 cre= 1.0479634 acc= 0.6528
step= 8500 cre= 1.0552124 acc= 0.659
step= 9000 cre= 1.038259 acc= 0.6674
step= 9500 cre= 1.0385478 acc= 0.6726
step= 10000 cre= 1.0463612 acc= 0.6774
step= 10500 cre= 1.0282755 acc= 0.6812
step= 11000 cre= 1.02937 acc= 0.683
step= 11500 cre= 1.0378207 acc= 0.6846
step= 12000 cre= 1.018677 acc= 0.6868
step= 12500 cre= 1.0205232 acc= 0.6872
step= 13000 cre= 1.02

In [48]:
#최종적인 정답률 구하기
acc = sess.run(accuracy, feed_dict={x:test_pat, y_:test_ans})
print('정답률 =',acc)

sess.close()

정답률 = 0.6906
