## Tensor
텐서(Tensor) : 파이토치에서 다양한 수식을 계산하는데 사용하는 기본적 자료구조

* 차원(랭크) 0 : 숫자가 1개(scalar)
* 차원(랭크) 1 : 일렬로 숫자가 나열(vector)
* 차원(랭크) 2 : 숫자를 가로, 세로로 나열(matrix)
* 차원(랭크) n : n차원(n-tensor)


In [1]:
import torch

# 3x3 텐서 선언
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)

print('size', x.size())
print('shape', x.shape)
print('rank', x.ndim)

C:\Users\LUDOBICO\AppData\Roaming\Python\Python37\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
size torch.Size([3, 3])
shape torch.Size([3, 3])
rank 2


딥러닝 연산 과정중 특정 Attention Layer 또는 데이터 간의 합성곱을 수행할 때 각 Tensor가 서로 다른 형태일 경우, 다음과 같이 `unsqueeze`를 통해 차원을 늘린 뒤 곱하고, 이후에 `squeeze`로 불필요한것을 다시 삭제한 뒤 FC에 넣는 형태로 많이 사용된다.

In [2]:
# 텐서 차원 늘리기 (dim = 0번째 자리에 차원 추가)
x = torch.unsqueeze(x, 0)
print(x)
print('size:', x.size())
print('shape:',x.shape)
print('rank:',x.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
size: torch.Size([1, 3, 3])
shape: torch.Size([1, 3, 3])
rank: 3


이 외에도 `view()`함수를 통해 직접 모양을 변경할 수 있다.

In [3]:
x = x.view(9)
print(x)
print('size:', x.size())
print('shape:',x.shape)
print('rank:',x.ndim)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
size: torch.Size([9])
shape: torch.Size([9])
rank: 1


## 텐서간 행렬곱
* a의 열 수와 b의 행 수는 동일해야 한다.
* 행렬곱 a x b의 결과 행렬의 행 개수는 a와 같고, 열의 개수는 b와 같다.

In [5]:
import torch

w = torch.randn(5,3, dtype=torch.float)
x = torch.tensor([[1.0, 2.0],[3.0, 4.0],[5.0, 6.0]])

print('w size:', w.size())
print('x size:', x.size())
print('w:',w)
print('x:',x)

w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
w: tensor([[-0.4367,  1.5152,  0.1166],
        [-1.3173,  0.6072, -0.1277],
        [-0.4242,  0.2385,  1.3095],
        [ 0.8849,  0.8043, -0.8749],
        [-0.6930, -0.4887,  1.8551]])
x: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [8]:
b = torch.randn(5,2,dtype=torch.float)
print('b size:',b.size())
print('b:',b)

b size: torch.Size([5, 2])
b: tensor([[-0.6464,  0.8179],
        [-1.4951, -0.1950],
        [-0.3608,  0.3899],
        [-0.4352,  0.8767],
        [ 0.3300,  0.3973]])


In [6]:
wx = torch.mm(w,x)
print('wx size:',wx.size())
print('ws:',wx)

wx size: torch.Size([5, 2])
ws: tensor([[ 4.6920,  5.8871],
        [-0.1340, -0.9717],
        [ 6.8385,  7.9622],
        [-1.0770, -0.2628],
        [ 7.1166,  7.7901]])


In [9]:
result = wx+b
print('result size:',result.size())
print('result:',result)


result size: torch.Size([5, 2])
result: tensor([[ 4.0456,  6.7050],
        [-1.6291, -1.1667],
        [ 6.4777,  8.3521],
        [-1.5122,  0.6139],
        [ 7.4466,  8.1874]])
